AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'templates/**/*'
    - 'features/**/*'
    - 'docs/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes